### ISSUE TITLE
Don't trim intentional whitespace

### ISSUE THREAD

**Issue by NomarCub** [superDuperCyberTechno/obsidian-code-copy#5]
There are situations where an additional empty line in a code block can be intentional. E.g. in order to paste code it into a shell and "hit enter" just by pasting.
The following code blocks produce the same content on the clipboard, and they shouldn't.

```
a
b
```

```
a
b

```

**Comment by NomarCub** [comment]
I'm fine with it working the way you described for my purposes now. But I'd rather it worked for all uses.
Trimming was necessary in the first place because all copied text ended with a newline character, right? Isn't it easier and more accurate to just correct for that one character as opposed to trimming everything?

**Comment by superDuperCyberTechno** [comment]
Yeah, I gues you're right. No need to fiddle too much with the code when there's no need. As far as I can tell it's safe to assume that the last character is always a newline, so that's what it removes as of now: https://github.com/superDuperCyberTechno/obsidian-code-copy/commit/fa07bf59c47667783ac7994a5ea4ef8fb9c9c002
